spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/challenge
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # ??? ??
        ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: verify0213@gmail.com
    password: ceip atbk wtff yufc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server.port: 8020
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
token: # ??? ????
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 300
  refresh-token-time: 500
gemini:
  url: ${GEMINI}