name: 테스트용 도커 빌드

on:
  push:
    branches:
      - main
      - jhs

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 1단계 코드 가져오기
        uses: actions/checkout@v2

      - name: 2단계 자바 설치 (JDK 17)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3단계 Gradle 빌드
        run: chmod +x ./gradlew && ./gradlew build

      - name: 도커 이미지 빌드
        run: docker build -t first-test-app .

      - name: 도커 이미지 푸쉬를 위한 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 도커 이미지 푸쉬
        run: docker push first-test-app

        #도커 3차 테스트용