name: 테스트용 도커 빌드

on:
  push:
    branches:
      - main
      - jhs

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 1단계 코드 가져오기
        uses: actions/checkout@v2

      - name: 2단계 자바 설치 (JDK 17)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3단계 Gradle 빌드
        run: chmod +x ./gradlew && ./gradlew build

      - name: .env 파일을 사용해 환경 변수 설정
        run: |
          if [ -f $GITHUB_WORKSPACE/.env ]; then
            echo "DOCKER_USERNAME=$(cat $GITHUB_WORKSPACE/.env | grep DOCKER_USERNAME | cut -d '=' -f2)" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=$(cat $GITHUB_WORKSPACE/.env | grep DOCKER_PASSWORD | cut -d '=' -f2)" >> $GITHUB_ENV
          else
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: 도커 이미지 빌드
        run: docker build -t ${{ env.DOCKER_USERNAME }}/first-test-app:latest .

      - name: 도커 이미지 푸쉬를 위한 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 도커 이미지 푸쉬
        run: docker push ${{ env.DOCKER_USERNAME }}/first-test-app

        #임시3